/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_potencia_1 (potencia_1_argument *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(argp->arg1, argp->arg2, rqstp));
}

static miArray *
_fibonacci_2 (int  *argp, struct svc_req *rqstp)
{
	return (fibonacci_2_svc(*argp, rqstp));
}

static miArray *
_suma_v_2 (suma_v_2_argument *argp, struct svc_req *rqstp)
{
	return (suma_v_2_svc(argp->arg1, argp->arg2, rqstp));
}

static miArray *
_resta_v_2 (resta_v_2_argument *argp, struct svc_req *rqstp)
{
	return (resta_v_2_svc(argp->arg1, argp->arg2, rqstp));
}

static miArray *
_product_v_2 (product_v_2_argument *argp, struct svc_req *rqstp)
{
	return (product_v_2_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_product_escalar_2 (product_escalar_2_argument *argp, struct svc_req *rqstp)
{
	return (product_escalar_2_svc(argp->arg1, argp->arg2, rqstp));
}

static float *
_media_aritmetica_2 (miArray  *argp, struct svc_req *rqstp)
{
	return (media_aritmetica_2_svc(*argp, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		potencia_1_argument potencia_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case suma:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case resta:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case multiplicacion:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case division:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case potencia:
		_xdr_argument = (xdrproc_t) xdr_potencia_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fibonacci_2_arg;
		suma_v_2_argument suma_v_2_arg;
		resta_v_2_argument resta_v_2_arg;
		product_v_2_argument product_v_2_arg;
		product_escalar_2_argument product_escalar_2_arg;
		miArray media_aritmetica_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case fibonacci:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_miArray;
		local = (char *(*)(char *, struct svc_req *)) _fibonacci_2;
		break;

	case suma_v:
		_xdr_argument = (xdrproc_t) xdr_suma_v_2_argument;
		_xdr_result = (xdrproc_t) xdr_miArray;
		local = (char *(*)(char *, struct svc_req *)) _suma_v_2;
		break;

	case resta_v:
		_xdr_argument = (xdrproc_t) xdr_resta_v_2_argument;
		_xdr_result = (xdrproc_t) xdr_miArray;
		local = (char *(*)(char *, struct svc_req *)) _resta_v_2;
		break;

	case product_v:
		_xdr_argument = (xdrproc_t) xdr_product_v_2_argument;
		_xdr_result = (xdrproc_t) xdr_miArray;
		local = (char *(*)(char *, struct svc_req *)) _product_v_2;
		break;

	case product_escalar:
		_xdr_argument = (xdrproc_t) xdr_product_escalar_2_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _product_escalar_2;
		break;

	case media_aritmetica:
		_xdr_argument = (xdrproc_t) xdr_miArray;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _media_aritmetica_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALC_BASIC);
	pmap_unset (CALCULADORA, CALC_COMP);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALC_BASIC, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALC_BASIC, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALC_COMP, calculadora_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALC_COMP, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALC_BASIC, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALC_BASIC, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALC_COMP, calculadora_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALC_COMP, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
